<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="9" failed="1" total="11" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Mercury Test Suite-Estimates" duration-ms="99586" started-at="2019-08-03T07:06:48Z" finished-at="2019-08-03T07:08:27Z">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="46341" started-at="2019-08-03T07:06:48Z" finished-at="2019-08-03T07:07:34Z">
      <class name="smokeTestCasesEstimatesTaxCalculations.TC01_Login">
        <test-method status="PASS" signature="setup()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.TC01_Login@56ac3a89]" name="setup" is-config="true" duration-ms="35821" started-at="2019-08-03T12:36:48Z" finished-at="2019-08-03T12:37:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login_page()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.TC01_Login@56ac3a89]" name="login_page" duration-ms="10481" started-at="2019-08-03T12:37:23Z" finished-at="2019-08-03T12:37:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_page -->
      </class> <!-- smokeTestCasesEstimatesTaxCalculations.TC01_Login -->
    </test> <!-- Login Test -->
    <test name="Taxes Calculations" duration-ms="51960" started-at="2019-08-03T07:07:35Z" finished-at="2019-08-03T07:08:27Z">
      <class name="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations">
        <test-method status="FAIL" signature="estimate_taxes()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_taxes" duration-ms="51891" started-at="2019-08-03T12:37:35Z" finished-at="2019-08-03T12:38:27Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[chrome not reachable
  (Session info: chrome=75.0.3770.142)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.09 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Sumit', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\SUMITK~1\AppData\Local\Temp\scoped_dir12004_11465}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=75.0.3770.142, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: c3022698981b582683a185cdeeae248b
*** Element info: {Using=xpath, value=//*[@class='dxmMenuItem']//*[text()='Data']}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=75.0.3770.142)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.17134 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 4.09 seconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'Sumit', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\SUMITK~1\AppData\Local\Temp\scoped_dir12004_11465}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=75.0.3770.142, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: c3022698981b582683a185cdeeae248b
*** Element info: {Using=xpath, value=//*[@class='dxmMenuItem']//*[text()='Data']}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:500)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:361)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at pageObjLibrary.EstimateTaxesCalculations.addWizardService(EstimateTaxesCalculations.java:245)
	at smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_taxes(estimate_misctaxescalculations.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_taxes -->
        <test-method status="SKIP" signature="estimate_taxes_wizard()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_taxes_wizard" duration-ms="1" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_taxes" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_taxes_wizard()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_taxes_wizard()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_taxes_wizard -->
        <test-method status="SKIP" signature="estimate_NoAction()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_NoAction" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_taxes_wizard" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_NoAction()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_NoAction()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_NoAction -->
        <test-method status="SKIP" signature="estimate_TC05()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC05" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_NoAction" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC05()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC05()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC05 -->
        <test-method status="SKIP" signature="estimate_TC06()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC06" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_TC05" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC06()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC06()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC06 -->
        <test-method status="SKIP" signature="estimate_TC04()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC04" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_TC06" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC04()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC04()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC04 -->
        <test-method status="SKIP" signature="estimate_TC07()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC07" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_TC04" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC07()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC07()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC07 -->
        <test-method status="SKIP" signature="estimate_TC08()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC08" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_TC07" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC08()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC08()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC08 -->
        <test-method status="SKIP" signature="estimate_TC09()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC09" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_TC08" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC09()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC09()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC09 -->
        <test-method status="SKIP" signature="estimate_TC10()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5]" name="estimate_TC10" duration-ms="0" started-at="2019-08-03T12:38:27Z" depends-on-methods="smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations.estimate_TC09" finished-at="2019-08-03T12:38:27Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method estimate_misctaxescalculations.estimate_TC10()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method estimate_misctaxescalculations.estimate_TC10()[pri:0, instance:smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations@10bdf5e5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- estimate_TC10 -->
      </class> <!-- smokeTestCasesEstimatesTaxCalculations.estimate_misctaxescalculations -->
    </test> <!-- Taxes Calculations -->
  </suite> <!-- Mercury Test Suite-Estimates -->
</testng-results>
